apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  azurestorageaccountname: c2hhcnJ5c2ZpbGU=
  azurestorageaccountkey: RzV4Z2g3WVNNNDFyYXA1aHU2aytlTTBlc05FakJSRWxJcFJ1ei8rQmNMcktwbkVValBoVlh0emttSW9SMGlKUUg1T2FST2JwNlduMlFQTVgzVCtoK1E9PQ==
