apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  azureFile:
    secretName: azure-storage-secret
    shareName: testfile