apiVersion: batch/v1
kind: Job
metadata:
  name: echo-job
spec:
  completions: 5
  parallelism: 2
  backoffLimit: 1
  template:
    spec:
      activeDeadlineSeconds: 10
      imagePullSecrets:
        - name: azureregcred
      containers:
      - name: echo-job
        image: sharry.azurecr.io/testdocker
      restartPolicy: Never
